services:
  - type: web
    name: animestream
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: animestream_db
          property: connectionString

databases:
  - name: animestream_db
    databaseName: animestream
    plan: free 