services:
  - type: web
    name: aniflix
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: starter
    scaling:
      minInstances: 1
      maxInstances: 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    autoDeploy: false
    healthCheckPath: /
    healthCheckTimeout: 100
    postDeployCommand: python -c "from app import initialize_data; initialize_data()"

databases:
  - name: animestream_db
    databaseName: animestream
    plan: free