services:
  - type: web
    name: animestream
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120 --workers 4
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: animestream_db
          property: connectionString
      - key: PORT
        sync: false
    buildFilter:
      paths:
        - requirements.txt
        - "**/*.py"
    autoDeploy: false
    healthCheckPath: /
    healthCheckTimeout: 100
    postDeployCommand: python -c "from app import initialize_data; initialize_data()"

databases:
  - name: animestream_db
    databaseName: animestream
    plan: free